name: release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    defaults:
        run:
          shell: bash
    steps:
    - uses: actions/checkout@v5
    - name: Install build dependencies
      run: ./.github/scripts/req.sh
    - name: Build packages
      run: |
        wget -q --no-check-certificate https://github.com/MiscPS3/NixSDK/releases/download/2023.09.17/bullseye-sdk.tar.gz -O psdk.tar.gz
        tar -C /usr/local/ -xzf psdk.tar.gz
        . ./.github/scripts/env.sh
        export C_DATE=$(date +'%m/%d/%Y')
        export C_SHA=${GITHUB_SHA:0:5}
        make pkg && export FILEMANAGER=1 && make pkg
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        name: "Automatic Release  ${{ vars.C_DATE }}"
        body: "Includes latest changes to the repository, not thoroughly tested."
        tag_name: "v${{ vars.C_SHA }}"
        files: |
          ./ManaGunZ*.pkg
          ./FileManager*.pkg
        prerelease: true
